export const data = [
        {
        id: 1,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "5-12-2021",
        month: "December",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shift",
        afternoonShift: "Completed Shift",
        eveningShift: "Completed Shift"
    },
    {
        id: 2,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "8-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shift",
        afternoonShift: "Missed Shift",
        eveningShift: "Missed Shift"
    },
    {
        id: 3,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "12-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shift",
        afternoonShift: "",
        eveningShift: "Missed Shift"
    },
    {
        id: 4,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "15-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "",
        afternoonShift: "Completed Shifts",
        eveningShift: ""
    },
    {
        id: 5,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "18-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shifts",
        afternoonShift: "Completed Shifts",
        eveningShift: ""
    },
    {
        id: 6,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "25-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shift",
        afternoonShift: "Missed Shift",
        eveningShift: "Missed Shift"
    },
    {
        id: 7,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "26-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shift",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 8,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "28-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shift",
        afternoonShift: "",
        eveningShift: "Completed Shift"
    },
    {
        id: 9,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "31-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shift",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 10,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "31-12-2021",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "",
        afternoonShift: "",
        eveningShift: "Missed Shift"
    },
    {
        id: 11,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "1-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shifts",
        afternoonShift: "",
        eveningShift: "Missed Shift"
    },
    {
        id: 12,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "1-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "",
        afternoonShift: "Completed Shifts",
        eveningShift: ""
    },
    {
        id: 13,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "3-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shifts",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 14,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "7-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shifts",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 15,
        type: "Nurse",
        shiftStatus: "Missed",
        shiftMessage: "Missed Shifts",
        date: "7-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Missed Shifts",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 16,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "9-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shifts",
        afternoonShift: "Completed Shifts",
        eveningShift: ""
    },
    {
        id: 17,
        type: "Nurse",
        shiftStatus: "Completed",
        shiftMessage: "Completed Shifts",
        date: "17-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "Completed Shifts",
        afternoonShift: "",
        eveningShift: ""
    },
    {
        id: 18,
        type: "Nurse",
        shiftStatus: "Pending",
        shiftMessage: "20 Shifts Available ",
        date: "21-01-2022",
        time: "Morning Shift",
        urgent: "false",
        morningShift: "5 Shifts Available",
        afternoonShift: "6 Shifts Available",
        eveningShift: "9 Shifts Available"
    },
    {
        id: 19,
        type: "Nurse",
        shiftStatus: "Pending",
        shiftMessage: "10 Shifts Available ",
        date: "24-01-2022",
        time: "Morning Shift",
        urgent: "true",
        morningShift: "2 Shifts Available",
        afternoonShift: "4 Shifts Available",
        eveningShift: "4 Shifts Available"
    },
    {
        id: 20,
        type: "Nurse",
        shiftStatus: "Pending",
        shiftMessage: "30 Shifts Available ",
        date: "31-01-2022",
        time: "Morning Shift",
        urgent: "true",
        morningShift: "8 Shifts Available",
        afternoonShift: "12 Shifts Available",
        eveningShift: "10 Shifts Available"
    },
    {
        id: 21,
        type: "Nurse",
        shiftStatus: "Pending",
        shiftMessage: "40 Shifts Available ",
        date: "2-02-2022",
        time: "Morning Shift",
        urgent: "true",
        morningShift: "8 Shifts Available",
        afternoonShift: "20 Shifts Available",
        eveningShift: "12 Shifts Available"
    }
]